### ISSUE TITLE
services.minepy-metrics.environment.FORGE_SERVER contains true, which is an invalid type, it should be a string, number, or a null

### ISSUE THREAD

**Issue by kellyhamlin** [Abydos12/minepy-metrics#1]
#: docker-compose up -d
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.minepy-metrics.environment.FORGE_SERVER contains True, which is an invalid type, it should be a string, number, or a null

Using your example, using docker-compose 1.23.2

**Comment by kellyhamlin** [comment]
Using "True" worked.

**Comment by Abydos12** [comment]
Thanks, I'll fix the doc !
